//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerChoiceTerm2
    {
        public int AnswerID { get; set; }
        public string AnswerName { get; set; }
        public Nullable<int> AnswerQuestionsID { get; set; }
        public Nullable<bool> AnswerTrue { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    
        public virtual ChoiseQuestionTerm2 ChoiseQuestionTerm2 { get; set; }
    }
}
