//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUser()
        {
            this.LoginSessions = new HashSet<LoginSession>();
            this.StudentComments = new HashSet<StudentComment>();
            this.StudentExams = new HashSet<StudentExam>();
            this.StudentExamsTerm2 = new HashSet<StudentExamsTerm2>();
            this.StudentSubjectNotInTerm1 = new HashSet<StudentSubjectNotInTerm1>();
            this.StudentT7laf = new HashSet<StudentT7laf>();
            this.SupportTickets = new HashSet<SupportTicket>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public Nullable<bool> EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> PhoneNumberConfirmed { get; set; }
        public Nullable<bool> TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public Nullable<bool> LockoutEnabled { get; set; }
        public Nullable<int> AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> Sho3baID { get; set; }
        public Nullable<int> MazhabID { get; set; }
        public Nullable<byte> StageID { get; set; }
        public Nullable<byte> RowID { get; set; }
        public Nullable<int> InstTypeID { get; set; }
        public string InstName { get; set; }
        public Nullable<int> InstCode { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CountryName { get; set; }
        public Nullable<byte> GroupID { get; set; }
        public Nullable<int> StudentNumber { get; set; }
        public Nullable<byte> GroupTest { get; set; }
        public Nullable<int> @new { get; set; }
        public Nullable<int> t7laf { get; set; }
    
        public virtual CountryTime CountryTime { get; set; }
        public virtual GroupNo GroupNo { get; set; }
        public virtual GroupNo GroupNo1 { get; set; }
        public virtual Institute Institute { get; set; }
        public virtual InstType InstType { get; set; }
        public virtual Mazhab Mazhab { get; set; }
        public virtual Row Row { get; set; }
        public virtual Sho3ba Sho3ba { get; set; }
        public virtual Stage Stage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginSession> LoginSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentComment> StudentComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentExam> StudentExams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentExamsTerm2> StudentExamsTerm2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSubjectNotInTerm1> StudentSubjectNotInTerm1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentT7laf> StudentT7laf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportTicket> SupportTickets { get; set; }
    }
}
