//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers1
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public Nullable<bool> EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> PhoneNumberConfirmed { get; set; }
        public Nullable<bool> TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public Nullable<bool> LockoutEnabled { get; set; }
        public Nullable<int> AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> Sho3baID { get; set; }
        public Nullable<int> MazhabID { get; set; }
        public Nullable<byte> StageID { get; set; }
        public Nullable<byte> RowID { get; set; }
        public Nullable<int> InstTypeID { get; set; }
        public string InstName { get; set; }
        public Nullable<int> InstCode { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CountryName { get; set; }
        public Nullable<byte> GroupID { get; set; }
        public Nullable<int> StudentNumber { get; set; }
        public Nullable<byte> GroupTest { get; set; }
        public string t7laf { get; set; }
        public string subject { get; set; }
        public string sub1 { get; set; }
        public string sub2 { get; set; }
        public string sub3 { get; set; }
        public string sub4 { get; set; }
        public string sub5 { get; set; }
        public string sub6 { get; set; }
        public string sub7 { get; set; }
        public string sub8 { get; set; }
        public string sub9 { get; set; }
        public string sub10 { get; set; }
        public string sub11 { get; set; }
        public string sub12 { get; set; }
        public string sub13 { get; set; }
        public string sub14 { get; set; }
        public string sub15 { get; set; }
        public string sub16 { get; set; }
        public string sub17 { get; set; }
        public string sub18 { get; set; }
        public string sub19 { get; set; }
        public string sub20 { get; set; }
        public string sub21 { get; set; }
        public string ids { get; set; }
    }
}
