//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiseQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChoiseQuestion()
        {
            this.AnswerChoices = new HashSet<AnswerChoice>();
            this.StudentChoiceExams = new HashSet<StudentChoiceExam>();
        }
    
        public int QuestionsID { get; set; }
        public string QuationTitle { get; set; }
        public Nullable<byte> QuestionLevelID { get; set; }
        public Nullable<double> degree { get; set; }
        public Nullable<bool> ApearForAll { get; set; }
        public Nullable<int> ExamID { get; set; }
        public Nullable<int> QuestionType { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string AssignBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<bool> Answertruefalse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerChoice> AnswerChoices { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual QuationType QuationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentChoiceExam> StudentChoiceExams { get; set; }
    }
}
