//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamsTerm2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamsTerm2()
        {
            this.ChoiseQuestionTerm2 = new HashSet<ChoiseQuestionTerm2>();
            this.ExamsInstTypeTerm2 = new HashSet<ExamsInstTypeTerm2>();
            this.StudentExamsTerm2 = new HashSet<StudentExamsTerm2>();
        }
    
        public int ExamsTerm2ID { get; set; }
        public string ExamName { get; set; }
        public Nullable<int> Duration { get; set; }
        public string RegisterBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<int> NoOfTry { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.TimeSpan> Examtime { get; set; }
        public Nullable<double> MaxDegree { get; set; }
        public Nullable<double> AvargeDeg { get; set; }
        public Nullable<int> JobGroup { get; set; }
        public Nullable<int> NoQus { get; set; }
        public Nullable<int> InstCode { get; set; }
        public Nullable<int> MazhabID { get; set; }
        public Nullable<int> SubjectsStageRowID { get; set; }
        public Nullable<byte> GroupNo { get; set; }
        public Nullable<System.DateTime> TimeDate { get; set; }
        public Nullable<System.TimeSpan> TimeFrom { get; set; }
        public Nullable<System.TimeSpan> TimeTo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string AssignBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<bool> ISRevision { get; set; }
        public Nullable<bool> MixArEn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChoiseQuestionTerm2> ChoiseQuestionTerm2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamsInstTypeTerm2> ExamsInstTypeTerm2 { get; set; }
        public virtual GroupNo GroupNo1 { get; set; }
        public virtual Institute Institute { get; set; }
        public virtual Mazhab Mazhab { get; set; }
        public virtual SubjectsStageRow SubjectsStageRow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentExamsTerm2> StudentExamsTerm2 { get; set; }
    }
}
