//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson.Models
{
    using System;
    
    public partial class Get_MultiquestionAnswer_Result4
    {
        public string AnswerName { get; set; }
        public Nullable<bool> AnswerTrue { get; set; }
        public string ExamTypes { get; set; }
        public string QuestionLevelName { get; set; }
        public Nullable<int> Year1 { get; set; }
        public string RegisterBy { get; set; }
        public Nullable<System.DateTime> RevisionDate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> revision { get; set; }
        public Nullable<byte> degree { get; set; }
        public string QuationTitle { get; set; }
        public int QuestionsID { get; set; }
        public Nullable<int> QuationTypeID { get; set; }
    }
}
