//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginSession
    {
        public System.Guid Id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string JWTToken { get; set; }
        public string BrowserType { get; set; }
        public string DeviceType { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string Location { get; set; }
        public string FirebaseToken { get; set; }
        public string RemoteIP { get; set; }
        public Nullable<long> ExpiresIn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string stdid { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
