//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuationType()
        {
            this.ChoiseQuestions = new HashSet<ChoiseQuestion>();
            this.ChoiseQuestionTerm2 = new HashSet<ChoiseQuestionTerm2>();
        }
    
        public int QuationTypeID { get; set; }
        public string QuationTypeName { get; set; }
        public string QuationTypeNameEn { get; set; }
        public string QuationTypeNameFr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChoiseQuestion> ChoiseQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChoiseQuestionTerm2> ChoiseQuestionTerm2 { get; set; }
    }
}
