//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class st
    {
        public string UserName { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> Sho3baID { get; set; }
        public Nullable<int> MazhabID { get; set; }
        public Nullable<byte> StageID { get; set; }
        public Nullable<byte> RowID { get; set; }
        public Nullable<int> InstTypeID { get; set; }
        public string InstName { get; set; }
        public Nullable<int> InstCode { get; set; }
        public string CountryName { get; set; }
        public Nullable<byte> GroupID { get; set; }
        public int StudentNumber { get; set; }
        public string Note { get; set; }
        public Nullable<bool> @new { get; set; }
        public Nullable<int> sub1 { get; set; }
        public Nullable<int> sub2 { get; set; }
        public Nullable<int> sub3 { get; set; }
        public Nullable<int> sub4 { get; set; }
        public Nullable<int> sub5 { get; set; }
        public Nullable<int> sub6 { get; set; }
        public Nullable<int> sub7 { get; set; }
        public Nullable<int> sub8 { get; set; }
        public Nullable<int> sub9 { get; set; }
        public Nullable<int> sub10 { get; set; }
        public Nullable<int> sub11 { get; set; }
        public Nullable<int> sub12 { get; set; }
        public Nullable<int> sub13 { get; set; }
        public Nullable<int> sub14 { get; set; }
        public Nullable<int> sub15 { get; set; }
        public Nullable<int> sub16 { get; set; }
        public Nullable<int> sub17 { get; set; }
        public Nullable<int> sub18 { get; set; }
        public Nullable<int> sub19 { get; set; }
        public Nullable<int> sub20 { get; set; }
        public Nullable<int> sub21 { get; set; }
    }
}
