//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentChoiceExamTerm2
    {
        public int StudentChoiceExamTerm2ID { get; set; }
        public Nullable<int> QuestionsID { get; set; }
        public Nullable<int> AnswerStudent { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string RegisterBy { get; set; }
        public Nullable<double> GradeStudent { get; set; }
        public Nullable<double> GradeFinal { get; set; }
        public Nullable<System.DateTime> TimeSolved { get; set; }
        public Nullable<System.Guid> StudentExamID { get; set; }
        public string AnswerStudentText { get; set; }
    
        public virtual ChoiseQuestionTerm2 ChoiseQuestionTerm2 { get; set; }
        public virtual StudentExamsTerm2 StudentExamsTerm2 { get; set; }
    }
}
