//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSubjectNotInTerm1
    {
        public int StudentSubjectNotInTerm1ID { get; set; }
        public string StudentID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> stno { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
