//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentExam()
        {
            this.StudentChoiceExams = new HashSet<StudentChoiceExam>();
        }
    
        public string SudentID { get; set; }
        public Nullable<int> ExamID { get; set; }
        public Nullable<System.DateTime> StartAt { get; set; }
        public string RegisterBy { get; set; }
        public Nullable<int> ReminaingTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> EndAt { get; set; }
        public Nullable<System.DateTime> LastClickOnQuestion { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> TokonExpireTime { get; set; }
        public System.Guid StudentExamID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Exam Exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentChoiceExam> StudentChoiceExams { get; set; }
    }
}
