//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectsStageRow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubjectsStageRow()
        {
            this.Exams = new HashSet<Exam>();
            this.ExamsTerm2 = new HashSet<ExamsTerm2>();
        }
    
        public int SubjectsStageRowID { get; set; }
        public Nullable<int> StageRow { get; set; }
        public Nullable<int> SubjectsID { get; set; }
        public Nullable<int> Sho3baID { get; set; }
        public Nullable<bool> IsForSpecialInst { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam> Exams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamsTerm2> ExamsTerm2 { get; set; }
        public virtual Sho3ba Sho3ba { get; set; }
        public virtual StageRow StageRow1 { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
